///////////////////////////////////////////////////////////
//  Outcome.cs
//  Implementation of the Class Outcome
//  Generated by Enterprise Architect
//  Created on:      16-dets-2019 16:16:30
//  Original author: marti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public class Outcome {

		public Outcome(){

		}

	}//end Outcome

}//end namespace System