///////////////////////////////////////////////////////////
//  ProcessManager.cs
//  Implementation of the Class ProcessManager
//  Generated by Enterprise Architect
//  Created on:      16-dets-2019 16:16:30
//  Original author: marti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
namespace System {
	public class ProcessManager {

		private System.Process m_Process;

		public ProcessManager(){

		}

		public Process Process{
			get{
				return m_Process;
			}
			set{
				m_Process = value;
			}
		}

	}//end ProcessManager

}//end namespace System