///////////////////////////////////////////////////////////
//  Process.cs
//  Implementation of the Class Process
//  Generated by Enterprise Architect
//  Created on:      16-dets-2019 16:16:30
//  Original author: marti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
namespace System {
	public class Process {

		private System.Task m_Task;
		private System.Role m_Role;

		public Process(){

		}

		public Role Role{
			get{
				return m_Role;
			}
			set{
				m_Role = value;
			}
		}

		public Task Task{
			get{
				return m_Task;
			}
			set{
				m_Task = value;
			}
		}

	}//end Process

}//end namespace System