///////////////////////////////////////////////////////////
//  RelationshipType.cs
//  Implementation of the Enumeration RelationshipType
//  Generated by Enterprise Architect
//  Created on:      16-dets-2019 16:16:31
//  Original author: marti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public enum RelationshipType : int {

	}//end RelationshipType

}//end namespace System