///////////////////////////////////////////////////////////
//  Relationship.cs
//  Implementation of the Class Relationship
//  Generated by Enterprise Architect
//  Created on:      16-dets-2019 16:16:31
//  Original author: marti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
namespace System {
	public class Relationship {

		private System.Role m_Role;
		private System.RelationshipType m_RelationshipType;

		public Relationship(){

		}

		public RelationshipType RelationshipType{
			get{
				return m_RelationshipType;
			}
			set{
				m_RelationshipType = value;
			}
		}

		public Role Role{
			get{
				return m_Role;
			}
			set{
				m_Role = value;
			}
		}

	}//end Relationship

}//end namespace System