///////////////////////////////////////////////////////////
//  Role.cs
//  Implementation of the Class Role
//  Generated by Enterprise Architect
//  Created on:      16-dets-2019 16:16:31
//  Original author: marti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public class Role {

		public Role(){

		}

	}//end Role

}//end namespace System