///////////////////////////////////////////////////////////
//  Task.cs
//  Implementation of the Class Task
//  Generated by Enterprise Architect
//  Created on:      16-dets-2019 16:16:31
//  Original author: marti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
namespace System {
	public class Task : Relationship {

		private System.Outcome m_Outcome;

		public Task(){

		}

		public Outcome Outcome{
			get{
				return m_Outcome;
			}
			set{
				m_Outcome = value;
			}
		}

	}//end Task

}//end namespace System